version: 2
updates:
  - package-ecosystem: "pip"
    directory: ".github/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
