version: '3'
services:
  gymdl:
    image: ghcr.io/nichuanfang/gymdl:latest
    container_name: gymdl
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
     #必须挂载配置文件否则项目无法启动
      - ./config.json:/app/config.json
      # 数据目录  目录结构和项目的data结构一致
      - ./data/bin:/app/data/bin
      - ./data/dist:/app/data/dist
      - ./data/logs:/app/data/logs
      - ./data/temp:/app/data/temp
      # pip 缓存目录
      - ./.pipcache:/root/.cache/pip
    expose:
      #api端口
      - 8080
    networks:
      - mynet
    restart: always

networks:
  mynet:
    external: true