name: 🐛 Bug Report
description: 提交一个错误报告以帮助我们改进 gymdl
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        感谢你提交 bug！请尽量提供完整的信息以便我们快速定位问题

  - type: dropdown
    id: os
    attributes:
      label: 🖥 操作系统
      description: 请选择运行 gymdl 的操作系统
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: dropdown
    id: deploy_method
    attributes:
      label: 🧩 部署方式
      description: 请选择你运行 gymdl 的方式
      options:
        - Docker
        - 可执行文件
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📦 gymdl 版本
      description: |
        运行时使用的 gymdl 版本号  
        - **Docker 部署**：填写镜像标签（例如：`ghcr.io/nichuanfang/gymdl:v1.0.5`）  
        - **可执行文件部署**：填写程序版本号（例如：`v1.0.5`）
      placeholder: 例如：v1.0.5 或 ghcr.io/nichuanfang/gymdl:v1.0.5
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
          **以下字段仅在部署方式为「可执行文件」时需要填写** ⬇️ 如果你选择了 Docker，请留空即可。

  - type: input
    id: yt-dlp-version
    attributes:
      label: 🎞 yt-dlp 版本
      description: 可执行文件部署时使用的 yt-dlp 版本
      placeholder: 例如：2025.10.22

  - type: input
    id: gamdl-version
    attributes:
      label: 🎵 gamdl 版本
      description: 可执行文件部署时使用的 gamdl 版本
      placeholder: 例如：2.7.2

  - type: input
    id: spotdl-version
    attributes:
      label: 🎧 spotdl 版本
      description: 可执行文件部署时使用的 spotdl 版本
      placeholder: 例如：4.4.3

  - type: dropdown
    id: n_m3u8dl-re-installed
    attributes:
      label: 📺 N_m3u8DL-RE
      description: 是否已安装 N_m3u8DL-RE？
      options:
        - 已安装
        - 未安装
    validations:
      required: false

  - type: dropdown
    id: ffmpeg-ffprobe-installed
    attributes:
      label: 🎬 ffmpeg / ffprobe
      description: 是否已安装 ffmpeg 和 ffprobe？
      options:
        - 已安装
        - 未安装
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: ❗ 问题描述
      description: 请详细描述你遇到的问题，包括预期结果与实际结果
      placeholder: 出现了什么？你期望的结果是什么？
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 🔁 复现步骤
      description: 请提供能复现问题的最小操作步骤或代码片段
      placeholder: |
        1. 安装 gymdl
        2. 执行了什么操作
        3. 观察错误输出
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📜 日志 / 错误输出
      description: 请粘贴完整的错误日志（如有）
      render: shell

  - type: textarea
    id: config
    attributes:
      label: ⚙️ 配置文件内容
      description: 请提供运行时使用的完整配置文件内容（请移除敏感信息，如 API Key 或密码）
      placeholder: |
        {
          "web_config": {
            "enable": false,
            "app_domain": "localhost",
            "https": false,
            "app_port": 8080,
            "gin_mode": "debug"
          },
          ...
        }
      render: json
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: ✅ 提交前确认
      options:
        - label: 我已使用 **最新版本** 测试此问题
          required: true
        - label: 我已检查现有 **issue**，确保此问题尚未被报告
          required: true
        - label: 我已阅读并理解 **README.md** 中的使用说明
          required: true
