name: Dependency Update

on:
#  schedule:
#    - cron: "0 2 * * *" # 每天凌晨2点
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Update Python dependencies
        working-directory: .github/dependency
        run: |
          pip-compile --upgrade requirements.txt --output-file=requirements.txt.tmp
          mv requirements.txt.tmp requirements.txt

#      - name: Install Python deps for update_tools.py
#        run: pip install -r .github/scripts/requirements.txt
#
#      - name: Update tools.txt dependencies
#        run: |
#          python .github/scripts/update_tools.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          body: "自动检测到依赖更新，更新 requirements.txt 和 tools.txt"
          branch: "dependency-update"
          base: "master"
          labels: "dependencies"