name: Build&Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/gymdl
          VERSION=${GITHUB_REF_NAME}
          
          echo "Building image: $IMAGE_NAME:$VERSION"
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .
          
          
          echo "Pushing image to GHCR..."
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Build
        run: make release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          draft: true
          generate_release_notes: true
          body: |
            * 这是 GitHub Actions 自动化部署，更新日志应该很快会手动更新
